#!/bin/bash

# BASH script to set or show CPU governer and frequencies
#
# Author: Seff Parker
# Version: 20190808

if [[ $UID -ne 0 ]]
	then
	echo "Re-invoking as ROOT user..."
	exec sudo $0 $*
fi

set_cpu_gov_freq () {
	for CPU_PATH in /sys/devices/system/cpu/cpu*/cpufreq
	do
		CPUID=$(echo $CPU_PATH | grep -Po cpu[0-9])
		echo -n "${CPUID} governor: "
		echo -n "$(cat $CPU_PATH/scaling_governor) ($(($(cat $CPU_PATH/cpuinfo_cur_freq) / 1000)) MHz)"
		if [[ "${GOVERNOR}" ]]
			then
			echo "${GOVERNOR}" > $CPU_PATH/scaling_governor
			echo $MIN_FREQ > $CPU_PATH/scaling_min_freq &> /dev/null || echo $MAX_FREQ > $CPU_PATH/scaling_max_freq
			echo $MAX_FREQ > $CPU_PATH/scaling_max_freq &> /dev/null || echo $MIN_FREQ > $CPU_PATH/scaling_min_freq 
			echo " --> $(cat $CPU_PATH/scaling_governor) ($(($(cat $CPU_PATH/cpuinfo_cur_freq) / 1000)) MHz)"
		else
			echo
		fi
	done
}

HW_MAX_FREQ=$(awk '{print $1}' /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies)
HW_MIN_FREQ=$(awk '{print $NF}' /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies)

case $1 in
	max* | high | performance)
		GOVERNOR="performance"
		MAX_FREQ=$HW_MAX_FREQ
		MIN_FREQ=$HW_MAX_FREQ
		;;
	min* | low | powersave)
		GOVERNOR="powersave"
		MAX_FREQ=$HW_MIN_FREQ
		MIN_FREQ=$HW_MIN_FREQ
		;;
	bal* | def* | ondemand)
		GOVERNOR="ondemand"
		MAX_FREQ=$HW_MAX_FREQ
		MIN_FREQ=$HW_MIN_FREQ
		;;
	"")
		# show current mode
		;;
	*)
		echo "Usage: $(basename $0) [mode]"
		echo "Modes are:"
		echo "	max, high, performance"
	        echo "	min, low, powersave"
		echo "	balanced, default, ondemand"
		exit 1	
		;;
esac

set_cpu_gov_freq
